### ISSUE TITLE
convert_name_to_target_numbers

### ISSUE THREAD

**Issue by jamie-sgro** [jamie-sgro/dashboard#10]
- Please modify the right chart to include the SDG target in the pop-up (you can find this info in the table below the dashboard)
- Rename the values of `DataPoint.name` to be the target numbers e.g 11.1.2 instead of "Assault"
- Order the bars by the SDG target number (This might just involve resorting the source data itself)

**Comment by andy-sgro** [comment]
Would it be better if the SDG target appeared in the immediate popup, or the delayed version of it?

**Comment by jamie-sgro** [comment]
Immediate please

**Comment by andy-sgro** [comment]
In the third point, should the bars be ordered in ascending or descending order?

**Comment by jamie-sgro** [comment]
Lowest at the top, highest at the bottom, just like the table below it

**Comment by andy-sgro** [comment]
Would this be an okay way to sort the data points, as by SDG target number?

House Need	11.1.1	0% of the population
Disaster	        11.5.1	0
Heritage	        11.5.2	0
Assault		11.7.2	0 per 100,000 population
Waste		11.6.2	10 (per recommendations from the CDC)
PM			11.7.1	50% of the built up area of cities
Econ Loss2	11.6.1	100% of urban solid waste
Transit		11.2.1	100% of the population
Civility	        11.3.2	A score of 5 on the UN-Habitat survey
Consumption	11.3.1	A ratio of 1
Affected	        11.4.1	$1,500 per capita in total expenditures

**Comment by jamie-sgro** [comment]
Just match the order of the table below it.

**Comment by andy-sgro** [comment]
Will do. For the descriptions, did you want target goal and id, or just the id?

**Comment by jamie-sgro** [comment]
Just the id. We could add I'd tooltip. To the pngs themselves later if we wanted with the actual number values
