### ISSUE TITLE
change_nonNormalValue_for_civility

### ISSUE THREAD

**Issue by jamie-sgro** [jamie-sgro/dashboard#22]
In `data.ts`, update the `nonNormalValue` where `name` == `"Civility"` to add "out of 5" at the end (e.g. “4 out of 5”).

Note in vsCode you can select `name: "Civility",` and press ctrl-d to multiselect, then press down -> down -> endKey -> and so on to add this text for all lines at once.

**Comment by mrvishalsharma** [comment]
Sir can you guide me on this even....as you have written to update the "nonNormalValue" in "Civility" were we have to update 
"out of 5"...
for example:-If this is the code
{
            name: "Civility",
            value: "0.583333333",
            nonNormalValue: "3.75",

},

//If  the nonNormalValue is 3.75 it will become 4
something like this?
{
            name: "Civility",
            value: "0.583333333",
            nonNormalValue: "4 out of 5",
          },

**Comment by jamie-sgro** [comment]
Thanks for seeking clarification, in the example you provided, let's keep the original values (e.g. no rounding) so your example would become:
```
// BEFORE
{
name: "Civility",
value: "0.583333333",
nonNormalValue: "3.75",
},

// AFTER
{
name: "Civility",
value: "0.583333333",
nonNormalValue: "3.75 out of 5",
},
```

**Comment by mrvishalsharma** [comment]
ok sir...and thank you so much for providing me an opportunity to contribute a little bit on your code.
