### ISSUE TITLE
change_nonNormalValue_for_transit

### ISSUE THREAD

**Issue by jamie-sgro** [jamie-sgro/dashboard#23]
In `data.ts`, update the `nonNormalValue` where `name` == `"Transit"` to add "%" at the end (e.g. 86.2%).

Note in vsCode you can select `name: "Transit",` and press ctrl-d to multiselect, then press down -> down -> endKey -> and so on to add this text for all lines at once.

**Comment by mrvishalsharma** [comment]
Sir i have fixed this bug.

**Comment by jamie-sgro** [comment]
Sounds great @mrvishalsharma .. feel free to submit a PR with the bugfixed and I can approve for merge
