### ISSUE TITLE
change-nonNormal_value_for_affected

### ISSUE THREAD

**Issue by jamie-sgro** [jamie-sgro/dashboard#24]
In `data.ts`, update the `nonNormalValue` where `name` == `"Affected"` to add "%" at the end (e.g. 86.2%).

- Additionally, round this value to **one decimal point**

Note in vsCode you can select `name: "Affected",` and press ctrl-d to multiselect, then press down -> down -> endKey -> and so on to add this text for all lines at once. Don't do this for the rounding however, only the percent symbol

**Comment by mrvishalsharma** [comment]
Sir can you clarify me one thing..In data.ts file you want to update where name=="Affected" with "%" symbol in nonNormalValue and
you want to round to one decimal point on this.....

for example:-  if the given code is this:-
{
  name: "Affected",
            value: "0.104394005",
            nonNormalValue: "23.79945071",
}

And the updated code should look like this?
{
  name: "Affected",
            value: "0.104394005",
            nonNormalValue: "24%",
}

**Comment by jamie-sgro** [comment]
Great question. With the rounding we'd have "23.8%", thus the final result:
```
{
  name: "Affected",
  value: "0.104394005",
  nonNormalValue: "23.8%",
}
```
