### ISSUE TITLE
change_description_for_civility

### ISSUE THREAD

**Issue by jamie-sgro** [jamie-sgro/dashboard#25]
1. In `data.ts` change the description for "Civility" to "Score of direct and regular participation by civil society in the urban planning and management of the primate city"
2. In `home.html` change the description for SDG 11.3.2 in the table section to that same: "Score of direct and regular participation by civil society in the urban planning and management of the primate city"

**Comment by mrvishalsharma** [comment]
Hello sir, I am unable to find data.ts file.

**Comment by jamie-sgro** [comment]
Hi Vishal, thanks for your contribution. I really appreciate it. `data.ts` can be found in `src/data.ts`. Comment below if you have any trouble accessing it

**Comment by mrvishalsharma** [comment]
Thank you so much sir, and now i have changed the description for "Civility"
