### ISSUE TITLE
Increase border-stroke value for rectangle object

### ISSUE THREAD

**Issue by jamie-sgro** [jamie-sgro/dashboard#31]
In `barplot.ts` the method `applyStrokeByName` should have a thicker stroke value so the rectangle pops out more.

Note this may involve updating the default stroke for all rectangles within the `Barplot.plot()` method

**Comment by jayeclark** [comment]
Hi @jamie-sgro and happy hacktoberfest. I think I can help with this! Here's what I have so far - I increased the stroke width to 2px and also added a slight opacity change. I *think* this was what was intended with this issue, but if not please point me in the right direction! If it looks good, I'll open a pull request. 

![strokeandopacity](https://user-images.githubusercontent.com/84106309/139542837-7361a11b-7a9e-4418-b911-82d56d207a8e.gif)

**Comment by jamie-sgro** [comment]
Hi @jayeclark, that looks phenomenal! I love the gif addition as well. Send over a PR and I'll take a look to merge
