### ISSUE TITLE
Fix axis image tick mark overlap

### ISSUE THREAD

**Issue by jayeclark** [jamie-sgro/dashboard#38]
The current image sizing and positioning on the Y-axis results in the images overlapping with/blending into the y-axis tick marks, and crowding the axis line.

I have a fix for this and can open a pull request if this is something that should be fixed (it's a minor design element, but it looks a little muddy to me as a user.)

**Current Image Size & Placement**
<img width="440" alt="Screen Shot 2021-10-31 at 10 12 09 AM" src="https://user-images.githubusercontent.com/84106309/139587802-0a61422c-97b8-42db-aba6-9cec29614ac1.png">

**Proposed Image Size & Placement**
<img width="457" alt="Screen Shot 2021-10-31 at 10 14 40 AM" src="https://user-images.githubusercontent.com/84106309/139587882-0a613191-e8b0-492c-9c04-5400a9ec61e1.png">

**Comment by jamie-sgro** [comment]
Great eye, and even if it's a smaller design element, I think these incremental improvements work as a significant improvement when taken as a whole.

I'm noticing that the clipping still occurs even when shortening the browser window height-wise as the images shrink. Feel free to assign me the PR whenever is convenient and I'll take a look!
